enum ActionButtonType {
    CREATE_NEXT_WORKFLOWUNIT = <any>"CREATE_NEXT_WORKFLOWUNIT",
    PIN_DROPDOWN = <any>"PIN_DROPDOWN",
    PIN_DROPDOWN_EMPTY_PROCESSOR = <any>"PIN_DROPDOWN_EMPTY_PROCESSOR",
    PIN_BUTTON = <any>"PIN_BUTTON",
    SET_INCONTACT = <any>"SET_INCONTACT",
    OPEN_FOLLOWUP_MODAL = <any>"SET_FOLLOWUP",
    DETAILS_DROPDOWN = <any>"DETAILS_DROPDOWN",
    DETAILS_TOGGLE_CLOSE_OR_OPEN = <any>"DETAILS_TOGGLE_CLOSE_OR_OPEN",
    DETAILS_OPEN_EDIT_MODAL = <any>"DETAILS_OPEN_EDIT_MODAL",
    DETAILS_OPEN_ROLLBACK_MODAL = <any>"DETAILS_OPEN_ROLLBACK_MODAL",
    DETAILS_OPEN_DELETE_MODAL = <any>"DETAILS_OPEN_DELETE_MODAL",
}
